# Generated by Django 5.0.3 on 2024-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
